### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by maniruz-rtech** [kjanko/python-fingerprint-recognition#5]
![issuse](https://user-images.githubusercontent.com/48088408/55540140-fd073000-56ca-11e9-8550-2deeccf8cbe5.png)

**Comment by maniruz-rtech** [comment]
![problem](https://user-images.githubusercontent.com/48088408/55546144-54130200-56d7-11e9-9f80-634b092a5bd4.png)

**Comment by kjanko** [comment]
Duplicate https://github.com/kjanko/python-fingerprint-recognition/issues/3

**Comment by pakinja** [comment]
Hello, first it is necessary to congratulate the author of this project. I'm trying to execute the project. At first I had the problem that I could not find the modules but that problem was solved, now it sends me an error:  `line 74, in main
    image_name = sys.argv[1]
IndexError: list index out of range`

![apppy](https://user-images.githubusercontent.com/15304390/55690019-b37c4680-5951-11e9-8141-2bffde95d7ee.png)

Can you help me?
Thanks!

**Comment by kjanko** [comment]
@pakinja read the documentation, you need to pass image names as parameters.

**Comment by maniruz-rtech** [comment]
Hi;i did so but still there is problem. i marked the enhance folder as directory but still image_enhance.py not able to import other .py file inside the enhance folder.08.04.2019, 14:52, "Kristijan Jankoski" <notifications@github.com>:@pakinja read the documentation, you need to pass image names as parameters.
